Working version for remove/upgrade/backup

diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -7,19 +7,6 @@
 source _common.sh
 source /usr/share/yunohost/helpers
 
-### Settings are automatically loaded as bash variables
-### in every app script context, therefore typically these will exist:
-### - $domain
-### - $path
-### - $language
-### - $install_dir
-### - $port
-### ...
-
-### In the context of upgrade,
-### - resources are automatically provisioned / updated / deleted (depending on existing resources)
-### - a safety backup is automatically created by the core and will be restored if the upgrade fails
-
 #=================================================
 # STOP SYSTEMD SERVICE
 #=================================================
@@ -28,36 +15,64 @@ ynh_script_progression "Stopping $app's systemd service..."
 ynh_systemctl --service="$app" --action="stop"
 
 #=================================================
-# ENSURE DOWNWARD COMPATIBILITY
+# INSTALL DEX APP FOR OAUTH2 / OIDC
 #=================================================
-#ynh_script_progression "Ensuring downward compatibility..."
+if ! yunohost app list | grep -q "id: $dex_app"; then
+  ynh_script_progression "Installing Dex..."
+  yunohost tools update
+  if yunohost app list | grep -q "$dex_domain$dex_path"; then
+    ynh_die "The domain provided for Dex is already used by another app. Please choose another one!"
+  fi
+  install_dex
+fi
 
-### N.B. : the following setting migration snippets are provided as *EXAMPLES*
-### of what you may want to do in some cases (e.g. a setting was not defined on
-### some legacy installs and you therefore want to initiaze stuff during upgrade)
+#=================================================
+# INSTALL NODEJS
+#=================================================
 
-# If db_name doesn't exist, create it
-# ynh_app_setting_set_default --key=db_name --value="$(ynh_sanitize_dbid --db_name=$app)"
+ynh_script_progression "Installing dependencies..."
 
-# If install_dir doesn't exist, create it
-# ynh_app_setting_set_default --key=install_dir --value="/var/www/$app"
+ynh_nodejs_install
 
 #=================================================
 # DOWNLOAD, CHECK AND UNPACK SOURCE
 #=================================================
 ynh_script_progression "Upgrading source files..."
 
-### ynh_setup_source can wipe the destination dir if called with --full_replace.
-### On upgrade, that is certainly what you want, to remove any old source file that
-### does not exist in the new version of the software.
-### You can list with --keep every file/directory to *not* wipe or overwrite,
-### useful for configuration files, data directories, or plugins.
-# Download, check integrity, uncompress and patch the source from manifest.toml
-ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=".env data"
+ynh_setup_source --dest_dir="$install_dir" --full_replace
+ynh_setup_source --dest_dir="$install_dir/livekit" --source_id="livekit" # --full-replace
 
-### $install_dir will automatically be initialized with some decent
-### permissions by default... however, you may need to recursively reapply
-### ownership to all files such as after the ynh_setup_source step
+ynh_exec_as_app mkdir -p "$install_dir/_build/venv"
+ynh_exec_as_app mkdir -p "$install_dir/_build/frontend"
+ynh_exec_as_app mkdir -p "$install_dir/_build/data/static"
+
+pushd "$install_dir/_build/venv"
+  ynh_exec_as_app python -m venv .
+  ynh_exec_as_app ./bin/pip install ../../src/backend
+popd
+
+pushd "$install_dir/src/backend"
+  # Collect the static resources
+  ynh_exec_as_app MEET_DATA_DIR="$install_dir/_build/data/static" DJANGO_CONFIGURATION=Build DJANGO_JWT_PRIVATE_SIGNING_KEY=Dummy \
+    STATIC_ROOT="$install_dir/src/backend" \
+    "$install_dir/_build/venv/bin/python" manage.py collectstatic --noinput
+  rdfind -makesymlinks true -followsymlinks true -makeresultsfile false "$install_dir/_build/data/static"
+  # Setup the database
+  # FIXME: cleanup the env variables.
+  ynh_exec_as_app \
+    MEET_DATA_DIR="$install_dir/_build/data/static" DJANGO_CONFIGURATION=Build DJANGO_JWT_PRIVATE_SIGNING_KEY=Dummy \
+    STATIC_ROOT="$install_dir/src/backend" \
+    DB_NAME=$db_name DB_USER=$db_name DB_PASSWORD=$db_pwd \
+    "$install_dir/_build/venv/bin/python" manage.py migrate
+
+popd
+
+pushd "$install_dir/src/frontend"
+  ynh_hide_warnings ynh_exec_as_app npm ci
+  ynh_hide_warnings ynh_exec_as_app NODE_ENV=production VITE_API_BASE_URL="https://${domain}" npm run build -- --outDir="$install_dir/_build/frontend" --emptyOutDir
+popd
+
+
 chown -R "$app:www-data" "$install_dir"
 
 #=================================================
@@ -65,44 +80,33 @@ chown -R "$app:www-data" "$install_dir"
 #=================================================
 ynh_script_progression "Updating $app's configuration files..."
 
-### Same as during install
-###
-### The file will automatically be backed-up if it's found to be manually modified (because
-### ynh_config_add keeps track of the file's checksum)
+ynh_config_add --template="env" --destination="$install_dir/.env"
 
-ynh_config_add --template="some_config_file" --destination="$install_dir/some_config_file"
+ynh_config_add --template="livekit.yaml" --destination="$install_dir/livekit/livekit.yaml"
 
-# FIXME: this should be handled by the core in the future
-### You may need to use chmod 600 instead of 400,
-### for example if the app is expected to be able to modify its own config
-chmod 400 "$install_dir/some_config_file"
-chown "$app:$app" "$install_dir/some_config_file"
+chmod 400 "$install_dir/livekit/livekit.yaml"
+chown "$app:$app" "$install_dir/livekit/livekit.yaml"
 
-### For more complex cases where you want to replace stuff using regexes,
-### you shoud rely on ynh_replace (which is basically a wrapper for sed)
-### When doing so, you also need to manually call ynh_store_file_checksum
-###
-### ynh_replace --match="match_string" --replace="replace_string" --file="$install_dir/some_config_file"
-### ynh_store_file_checksum "$install_dir/some_config_file"
+ynh_config_add --template="meet.py" --destination="$install_dir/meet-conf.py"
+chmod 400 "$install_dir/meet-conf.py"
+chown "$app:$app" "$install_dir/meet-conf.py"
 
 #=================================================
 # REAPPLY SYSTEM CONFIGURATIONS
 #=================================================
 ynh_script_progression "Upgrading system configurations related to $app..."
 
-### This should be a literal copypaste of what happened in the install's "System configuration" section
-
-ynh_config_add_phpfpm
-
 ynh_config_add_nginx
 
+# Create a dedicated systemd config
 ynh_config_add_systemd
+ynh_config_add_systemd --service="${app}-livekit" --template="systemd-livekit.service"
 
-yunohost service add "$app" --description="A short description of the app" --log="/var/log/$app/$app.log"
+yunohost service add "$app" --description="Simple, high-performance videoconferencing solution" --log="/var/log/$app/$app.log"
+yunohost service add "$app-livekit" --description="Livekit for $app" --log="/var/log/$app/$app-livekit.log" --needs_exposed_ports "$port_tcp" "$port_livekit"
 
+# Use logrotate to manage application logfile(s)
 ynh_config_add_logrotate
-
-ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"
 
 #=================================================
 # START SYSTEMD SERVICE
@@ -110,6 +114,7 @@ ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failreg
 ynh_script_progression "Starting $app's systemd service..."
 
 ynh_systemctl --service="$app" --action="start"
+ynh_systemctl --service="${app}-livekit" --action="start"
 
 #=================================================
 # END OF SCRIPT
